---
title: "Group 3 Project"
output:
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: inline
---


```{r setup, include=FALSE}
library(tidyverse)
library(readr)
library(readxl)
library(stringr)
povertyRate = read_xls("est19all.xls", col_names = TRUE, skip = 3) %>%
  filter(`Postal Code` == "WI")
#crimeData = read_xls("wisconsin.xls", skip = 5)
wiDOJ = read_csv("wi_doj_crime.csv") %>%
  filter(ReportYear == 2019)
```

```{r, include=FALSE}
wiCrimeData = wiDOJ %>%
  group_by(OffenseDescription, County) %>%
  summarise(count = sum(OffenseCount)) %>%
  pivot_wider(names_from = OffenseDescription, values_from = count)

category = wiDOJ %>%
  group_by(County, Category) %>%
  summarize(total = sum(OffenseCount)) %>%
  pivot_wider(names_from = Category, values_from = total) %>%
  select(-`Simple Assault`)

finalCrime = wiCrimeData %>%
  full_join(category)

df = finalCrime %>% 
  mutate(`Name` =str_c(County, " County")) %>%
  inner_join(povertyRate, by = "Name") %>%
  mutate(Population = round(as.numeric(`Poverty Estimate, All Ages`) * (100 / as.numeric(`Poverty Percent, All Ages`))))
  
finalDF = df %>% 
  select(-`Human Trafficking - Commercial Sex`, -`Human Trafficking - Involuntary Servitude`, -`Name`, -`State FIPS Code`, -`County FIPS Code`, -`Postal Code`) %>%
  select(-starts_with("90%"))
#fullCrime = crimeData %>%
#  mutate(`Name` =str_c(County, " County"))

#metro = c(rep("Metropolitan", 24), rep("Nonmetropolitan", 39))
#df = fullCrime %>%
#  inner_join(povertyRate, by = "Name") %>%
#  mutate(Population = round(as.numeric(`Poverty Estimate, All Ages`) * (100 / as.numeric(`Poverty Percent, All Ages`)))) %>%
#  mutate(`Metropolitan/Nonmetropolitan` = metro)
```

```{r}
ggplot(finalDF) + geom_col(aes(x = reorder(County, -Population), y = `Violent Crime`/(Population/100000)), fill = "navy") + theme(axis.text.x = element_text(angle = 90, vjust = 0.5)) + xlab("County") + ylab("Amount of Violent Crime per 100,000") + ggtitle("Amount of violent crime in Wisconsin by County", "In 2019") 
```


